name: SailfishOS build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir output

    - name: Build armv7hl
      id: build_armv7hl
      uses: R1tschY/sailfish-build-rpm@v1
      with:
        release: 4.0.1.48
        arch: armv7hl

    - name: Build i486
      id: build_i486
      uses: R1tschY/sailfish-build-rpm@v1
      with:
        release: 4.0.1.48
        arch: i486
        
    - name: Build aarch64
      id: build_aarch64
      uses: R1tschY/sailfish-build-rpm@v1
      with:
        release: 4.0.1.48
        arch: aarch64        
      
    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: rpms
        path: RPMS   
        
    - uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        repo: CepiPerez/filecase-sailfish # defaults to current repo
        delete_tag_pattern: master # defaults to ""
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        

    - name: Create release
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
