name: SailfishOS build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir output

    - uses: R1tschY/sailfish-build-rpm@v1
      with:
        arch: "armv7hl"
        release: "4.1.0.24"
        fix-version: false
        
    - uses: R1tschY/sailfish-build-rpm@v1
      with:
        arch: "i486"
        release: "4.1.0.24"
        fix-version: false
        
    - uses: R1tschY/sailfish-build-rpm@v1
      with:
        arch: "aarch64"
        release: "4.1.0.24"
        fix-version: false        

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: rpms
        path: RPMS
        
    - name: Delete releases     
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        keep_latest: 3
        delete_release: true # default: false
        tag_name: master # tag name to delete
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
